<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Active Drivers Report</title>
    <style>
        * {
            box-sizing: border-box;
        }
        body {
            font-family: "Segoe UI", Arial, sans-serif;
            font-size: 12px;
            color: #2c3e50;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 22px;
            margin: 0;
            color: #1d3557;
        }
        .header p {
            font-size: 14px;
            color: #6c757d;
        }
        .summary {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
            flex-wrap: wrap;
            gap: 15px;
        }
        .card {
            flex: 1;
            min-width: 200px;
            background-color: #f1f3f5;
            border: 1px solid #ced4da;
            border-radius: 6px;
            padding: 15px;
        }
        .card p {
            margin: 5px 0;
            font-size: 13px;
        }
        .card strong {
            display: block;
            color: #343a40;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 8px 10px;
            font-size: 11.5px;
        }
        th {
            background-color: #e9ecef;
            text-align: left;
            color: #212529;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .status-badge {
            background-color: #28a745;
            color: #fff;
            padding: 4px 8px;
            border-radius: 10px;
            font-size: 10px;
            font-weight: bold;
            display: inline-block;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 10px;
            color: #6c757d;
            border-top: 1px solid #dee2e6;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Active Drivers Report</h1>
        <p>EFCTS Management System</p>
    </div>

    <div class="summary">
        <div class="card">
            <p><strong>Report Date:</strong> {{ $date }}</p>
            <p><strong>Carrier:</strong> {{ $carrierName }}</p>
            @if(count($filtros) > 0)
            <p><strong>Applied Filters:</strong> {{ implode(', ', $filtros) }}</p>
            @endif
        </div>
        <div class="card">
            <p><strong>Total Drivers:</strong> {{ $totalDrivers }}</p>
            <p><strong>Generated By:</strong> EFCTS System</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Registration Date</th>
                <th>Carrier</th>
                <th>License</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($drivers as $driver)
            <tr>
                <td>{{ $driver->id }}</td>
                <td>{{ $driver->full_name ?? 'N/A' }}</td>
                <td>{{ $driver->user->email ?? 'N/A' }}</td>
                <td>{{ date('m/d/Y', strtotime($driver->created_at)) }}</td>
                <td>{{ $driver->carrier->name ?? 'N/A' }}</td>
                <td>{{ $driver->primaryLicense->license_number ?? 'N/A' }}</td>
                <td><span class="status-badge">Active</span></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This document was automatically generated. EFCTS &copy; {{ date('Y') }}</p>
    </div>
</body>
</html>
