<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Equipment List Report</title>
    <style>
        * {
            box-sizing: border-box;
        }
        body {
            font-family: "Segoe UI", Arial, sans-serif;
            font-size: 12px;
            color: #2c3e50;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 22px;
            margin: 0;
            color: #1d3557;
        }
        .header p {
            font-size: 14px;
            color: #6c757d;
        }
        .summary {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
            flex-wrap: wrap;
            gap: 15px;
        }
        .card {
            flex: 1;
            min-width: 200px;
            background-color: #f1f3f5;
            border: 1px solid #ced4da;
            border-radius: 6px;
            padding: 15px;
        }
        .card p {
            margin: 5px 0;
            font-size: 13px;
        }
        .card strong {
            display: block;
            color: #343a40;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 8px 10px;
            font-size: 11.5px;
        }
        th {
            background-color: #e9ecef;
            text-align: left;
            color: #212529;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .status-badge {
            padding: 4px 8px;
            border-radius: 10px;
            font-size: 10px;
            font-weight: bold;
            display: inline-block;
            color: #fff;
        }
        .status-active {
            background-color: #28a745;
        }
        .status-suspended {
            background-color: #ffc107;
        }
        .status-out-of-service {
            background-color: #dc3545;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 10px;
            color: #6c757d;
            border-top: 1px solid #dee2e6;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Equipment List Report</h1>
        <p>EF Services Management System</p>
    </div>

    <div class="summary">
        <div class="card">
            <p><strong>Report Date:</strong> {{ $date }}</p>
            <p><strong>Carrier:</strong> {{ $carrierName }}</p>
            @if(count($filtros) > 0)
            <p><strong>Applied Filters:</strong> {{ implode(', ', $filtros) }}</p>
            @endif
        </div>
        <div class="card">
            <p><strong>Total Vehicles:</strong> {{ $totalVehicles }}</p>
            <p><strong>Generated By:</strong> EF Services System</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Unit #</th>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>VIN</th>
                <th>Carrier</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($vehicles as $vehicle)
            <tr>
                <td>{{ $vehicle->id }}</td>
                <td>{{ $vehicle->company_unit_number }}</td>
                <td>{{ $vehicle->vehicleMake->name ?? $vehicle->make }}</td>
                <td>{{ $vehicle->model }}</td>
                <td>{{ $vehicle->year }}</td>
                <td>{{ $vehicle->vin }}</td>
                <td>{{ $vehicle->carrier->name ?? 'N/A' }}</td>
                <td>
                    @if($vehicle->status == 'active')
                        <span class="status-badge status-active">Active</span>
                    @elseif($vehicle->status == 'suspended')
                        <span class="status-badge status-suspended">Suspended</span>
                    @elseif($vehicle->status == 'out_of_service')
                        <span class="status-badge status-out-of-service">Out of Service</span>
                    @else
                        {{ $vehicle->status }}
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This document was automatically generated. EF Services &copy; {{ date('Y') }}</p>
    </div>
</body>
</html>
