<script setup lang="ts">
import { Head, router } from '@inertiajs/vue3'
import { computed, reactive } from 'vue'
import Button from '@/components/Base/Button'
import FormInput from '@/components/Base/Form/FormInput.vue'
import Litepicker from '@/components/Base/Litepicker/Litepicker.vue'
import Lucide from '@/components/Base/Lucide'
import TomSelect from '@/components/Base/TomSelect/TomSelect.vue'
import RazeLayout from '@/layouts/RazeLayout.vue'
import ReportHero from './components/ReportHero.vue'
import ReportPagination from './components/ReportPagination.vue'
import ReportStats from './components/ReportStats.vue'
import { pickerOptions, statusTone, type PaginationLink } from './components/reportUtils'
declare function route(name: string, params?: any): string
defineOptions({ layout: RazeLayout })
interface Row { id: number; driver_name: string; source_carrier: string | null; target_carrier: string | null; migrated_at: string | null; migrated_by: string | null; status: string; reason: string; rolled_back_at: string | null; can_rollback: boolean }
const props = defineProps<{ filters: { search: string; date_from: string; date_to: string; source_carrier_id: string; target_carrier_id: string; driver_user_id: string; status: string }; migrations: { data: Row[]; links: PaginationLink[]; total: number }; stats: { total_migrations: number; completed_migrations: number; rolled_back_migrations: number; rollback_rate: number }; reasons: { reason: string; count: number }[]; carriers: { id: number; name: string }[]; drivers: { id: number; name: string }[]; statusOptions: { value: string; label: string }[] }>()
const filters = reactive({ ...props.filters })
const statCards = computed(() => [{ label: 'Total Migrations', value: props.stats.total_migrations, icon: 'ArrowRightLeft', tone: 'primary' }, { label: 'Completed', value: props.stats.completed_migrations, icon: 'BadgeCheck', tone: 'success' }, { label: 'Rolled Back', value: props.stats.rolled_back_migrations, icon: 'RotateCcw', tone: 'warning' }, { label: 'Rollback Rate', value: `${props.stats.rollback_rate}%`, icon: 'PieChart', tone: 'info' }])
function applyFilters() { router.get(route('admin.reports.migrations'), { search: filters.search || undefined, date_from: filters.date_from || undefined, date_to: filters.date_to || undefined, source_carrier_id: filters.source_carrier_id || undefined, target_carrier_id: filters.target_carrier_id || undefined, driver_user_id: filters.driver_user_id || undefined, status: filters.status || undefined }, { preserveState: true, preserveScroll: true, replace: true }) }
</script>
<template>
    <Head title="Migrations Report" />
    <div class="grid grid-cols-12 gap-6">
        <div class="col-span-12"><ReportHero title="Migrations Report" subtitle="Immutable audit trail for driver migrations and rollbacks between carriers." icon="ArrowRightLeft" /></div>
        <div class="col-span-12"><ReportStats :cards="statCards" /></div>
        <div class="col-span-12 xl:col-span-9"><div class="box box--stacked p-5"><div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><FormInput v-model="filters.search" type="text" placeholder="Search driver or email..." @keyup.enter="applyFilters" /><TomSelect v-model="filters.source_carrier_id"><option value="">All Source Carriers</option><option v-for="carrier in carriers" :key="carrier.id" :value="String(carrier.id)">{{ carrier.name }}</option></TomSelect><TomSelect v-model="filters.target_carrier_id"><option value="">All Target Carriers</option><option v-for="carrier in carriers" :key="carrier.id" :value="String(carrier.id)">{{ carrier.name }}</option></TomSelect><TomSelect v-model="filters.driver_user_id"><option value="">All Drivers</option><option v-for="driver in drivers" :key="driver.id" :value="String(driver.id)">{{ driver.name }}</option></TomSelect><TomSelect v-model="filters.status"><option v-for="option in statusOptions" :key="option.value || 'all'" :value="option.value">{{ option.label }}</option></TomSelect><Litepicker v-model="filters.date_from" :options="pickerOptions" /><Litepicker v-model="filters.date_to" :options="pickerOptions" /><div class="flex gap-3 xl:col-span-2"><Button variant="primary" class="w-full" @click="applyFilters">Apply</Button><Button variant="outline-secondary" class="w-full" @click="filters.search=''; filters.date_from=''; filters.date_to=''; filters.source_carrier_id=''; filters.target_carrier_id=''; filters.driver_user_id=''; filters.status=''; applyFilters()">Reset</Button></div></div></div></div>
        <div class="col-span-12 xl:col-span-3"><div class="box box--stacked p-5"><h2 class="mb-4 text-base font-semibold text-slate-800">Migration Reasons</h2><div class="space-y-3 text-sm"><div v-for="reason in reasons" :key="reason.reason" class="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3"><span class="text-slate-600">{{ reason.reason }}</span><span class="font-medium text-slate-800">{{ reason.count }}</span></div><div v-if="!reasons.length" class="text-slate-500">No reasons found.</div></div></div></div>
        <div class="col-span-12"><div class="box box--stacked overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left font-semibold text-slate-600">Driver</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Source</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Target</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Migrated</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Status</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Reason</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white"><tr v-for="row in migrations.data" :key="row.id"><td class="px-5 py-4 font-medium text-slate-800">{{ row.driver_name }}</td><td class="px-5 py-4 text-slate-600">{{ row.source_carrier || 'N/A' }}</td><td class="px-5 py-4 text-slate-600">{{ row.target_carrier || 'N/A' }}</td><td class="px-5 py-4 text-slate-600"><div>{{ row.migrated_at || 'N/A' }}</div><div class="text-xs text-slate-500">{{ row.migrated_by || 'N/A' }}</div></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-medium" :class="statusTone(row.status)">{{ row.status }}</span></td><td class="px-5 py-4 text-slate-600"><div>{{ row.reason }}</div><div class="text-xs text-slate-500">Rollback: {{ row.rolled_back_at || 'Not rolled back' }}</div></td></tr><tr v-if="!migrations.data.length"><td colspan="6" class="px-5 py-10 text-center text-slate-500">No migration records matched the current filters.</td></tr></tbody></table></div><div class="border-t border-slate-100 p-4"><ReportPagination :links="migrations.links" /></div></div></div>
    </div>
</template>
