<script setup lang="ts">
import { Head } from '@inertiajs/vue3'
import RazeLayout from '@/layouts/RazeLayout.vue'
import ReportHero from './components/ReportHero.vue'

defineOptions({ layout: RazeLayout })

const props = defineProps<{ trip: Record<string, any>; entries: any[]; violations: any[]; gpsPoints: any[] }>()
</script>

<template>
    <Head :title="`Trip ${trip.trip_number}`" />
    <div class="grid grid-cols-12 gap-6">
        <div class="col-span-12"><ReportHero :title="`Trip ${trip.trip_number}`" subtitle="Trip detail with HOS entries, GPS points, and linked violations." icon="Route" /></div>
        <div class="col-span-12 xl:col-span-6"><div class="box box--stacked p-6"><h2 class="mb-4 text-lg font-semibold text-slate-800">Trip Summary</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2 text-sm"><div><div class="text-slate-500">Driver</div><div class="font-medium text-slate-800">{{ trip.driver_name }}</div></div><div><div class="text-slate-500">Carrier</div><div class="font-medium text-slate-800">{{ trip.carrier_name || 'N/A' }}</div></div><div><div class="text-slate-500">Vehicle</div><div class="font-medium text-slate-800">{{ trip.vehicle_label }}</div></div><div><div class="text-slate-500">Status</div><div class="font-medium text-slate-800">{{ trip.status }}</div></div><div><div class="text-slate-500">Origin</div><div class="font-medium text-slate-800">{{ trip.origin_address || 'N/A' }}</div></div><div><div class="text-slate-500">Destination</div><div class="font-medium text-slate-800">{{ trip.destination_address || 'N/A' }}</div></div><div><div class="text-slate-500">Scheduled Start</div><div class="font-medium text-slate-800">{{ trip.scheduled_start || 'N/A' }}</div></div><div><div class="text-slate-500">Scheduled End</div><div class="font-medium text-slate-800">{{ trip.scheduled_end || 'N/A' }}</div></div></div></div></div>
        <div class="col-span-12 xl:col-span-6"><div class="box box--stacked p-6"><h2 class="mb-4 text-lg font-semibold text-slate-800">Notes</h2><div class="space-y-4 text-sm"><div><div class="text-slate-500">Description</div><div class="font-medium text-slate-800">{{ trip.description || 'N/A' }}</div></div><div><div class="text-slate-500">Internal Notes</div><div class="font-medium text-slate-800">{{ trip.notes || 'N/A' }}</div></div><div><div class="text-slate-500">Driver Notes</div><div class="font-medium text-slate-800">{{ trip.driver_notes || 'N/A' }}</div></div></div></div></div>
        <div class="col-span-12 xl:col-span-6"><div class="box box--stacked p-6"><h2 class="mb-4 text-lg font-semibold text-slate-800">HOS Entries</h2><div class="space-y-3 text-sm"><div v-for="entry in entries" :key="entry.id" class="rounded-xl border border-slate-200 p-4"><div class="font-medium text-slate-800">{{ entry.date }} · {{ entry.status }}</div><div class="mt-1 text-slate-500">{{ entry.start_time || 'N/A' }} to {{ entry.end_time || 'N/A' }}</div><div class="mt-1 text-xs text-slate-500">Duration: {{ entry.duration_minutes }} min · {{ entry.location || 'No location' }}</div></div><div v-if="!entries.length" class="text-sm text-slate-500">No HOS entries found for this trip.</div></div></div></div>
        <div class="col-span-12 xl:col-span-6"><div class="box box--stacked p-6"><h2 class="mb-4 text-lg font-semibold text-slate-800">Violations</h2><div class="space-y-3 text-sm"><div v-for="violation in violations" :key="violation.id" class="rounded-xl border border-slate-200 p-4"><div class="font-medium text-slate-800">{{ violation.type }}</div><div class="mt-1 text-slate-500">{{ violation.date }} · {{ violation.severity }}</div><div class="mt-1 text-xs text-slate-500">Hours exceeded: {{ violation.hours_exceeded }} · Acknowledged: {{ violation.acknowledged ? 'Yes' : 'No' }}</div></div><div v-if="!violations.length" class="text-sm text-slate-500">No violations were linked to this trip.</div></div></div></div>
        <div class="col-span-12"><div class="box box--stacked p-6"><h2 class="mb-4 text-lg font-semibold text-slate-800">Recent GPS Points</h2><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left font-semibold text-slate-600">Recorded At</th><th class="px-4 py-3 text-left font-semibold text-slate-600">Latitude</th><th class="px-4 py-3 text-left font-semibold text-slate-600">Longitude</th><th class="px-4 py-3 text-left font-semibold text-slate-600">Speed MPH</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white"><tr v-for="point in gpsPoints" :key="point.id"><td class="px-4 py-3 text-slate-600">{{ point.recorded_at }}</td><td class="px-4 py-3 text-slate-600">{{ point.latitude }}</td><td class="px-4 py-3 text-slate-600">{{ point.longitude }}</td><td class="px-4 py-3 text-slate-600">{{ point.speed_mph ?? 'N/A' }}</td></tr><tr v-if="!gpsPoints.length"><td colspan="4" class="px-4 py-8 text-center text-slate-500">No GPS points available.</td></tr></tbody></table></div></div></div>
    </div>
</template>
