<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3'
import { computed, reactive } from 'vue'
import Button from '@/components/Base/Button'
import Litepicker from '@/components/Base/Litepicker/Litepicker.vue'
import Lucide from '@/components/Base/Lucide'
import TomSelect from '@/components/Base/TomSelect/TomSelect.vue'
import RazeLayout from '@/layouts/RazeLayout.vue'
import ReportHero from './components/ReportHero.vue'
import ReportPagination from './components/ReportPagination.vue'
import ReportStats from './components/ReportStats.vue'
import { pickerOptions, type PaginationLink } from './components/reportUtils'
declare function route(name: string, params?: any): string
defineOptions({ layout: RazeLayout })
interface Row { id: number; driver_name: string; carrier_name: string | null; trip_number: string | null; violation_type: string; severity: string; date: string | null; hours_exceeded: number; acknowledged: boolean }
const props = defineProps<{ filters: { carrier_id: string; driver_id: string; violation_type: string; severity: string; date_from: string; date_to: string; acknowledged: string; per_page: number }; violations: { data: Row[]; links: PaginationLink[]; total: number }; stats: { total_violations: number; acknowledged_count: number; unacknowledged_count: number; acknowledgment_rate: number }; carriers: { id: number; name: string }[]; drivers: { id: number; name: string }[]; violationTypes: { value: string; label: string }[]; severities: { value: string; label: string }[]; canFilterCarriers: boolean }>()
const filters = reactive({ ...props.filters })
const statCards = computed(() => [{ label: 'Total Violations', value: props.stats.total_violations, icon: 'AlertOctagon' }, { label: 'Acknowledged', value: props.stats.acknowledged_count, icon: 'BadgeCheck' }, { label: 'Unacknowledged', value: props.stats.unacknowledged_count, icon: 'BellRing' }, { label: 'Acknowledgment Rate', value: `${props.stats.acknowledgment_rate}%`, icon: 'PieChart' }])
function applyFilters() { router.get(route('admin.reports.violations'), { carrier_id: filters.carrier_id || undefined, driver_id: filters.driver_id || undefined, violation_type: filters.violation_type || undefined, severity: filters.severity || undefined, date_from: filters.date_from || undefined, date_to: filters.date_to || undefined, acknowledged: filters.acknowledged || undefined }, { preserveState: true, preserveScroll: true, replace: true }) }
</script>
<template>
    <Head title="Violations Report" />
    <div class="grid grid-cols-12 gap-6">
        <div class="col-span-12"><ReportHero title="Violations Report" subtitle="HOS violations by driver, type, severity, and acknowledgment state." icon="AlertOctagon"><template #actions><Button as="a" :href="route('admin.reports.violations-pdf', { ...filters })" variant="outline-secondary" class="gap-2"><Lucide icon="Download" class="h-4 w-4" />Export PDF</Button></template></ReportHero></div>
        <div class="col-span-12"><ReportStats :cards="statCards" /></div>
        <div class="col-span-12"><div class="box box--stacked p-5"><div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><TomSelect v-if="canFilterCarriers" v-model="filters.carrier_id"><option value="">All Carriers</option><option v-for="carrier in carriers" :key="carrier.id" :value="String(carrier.id)">{{ carrier.name }}</option></TomSelect><TomSelect v-model="filters.driver_id"><option value="">All Drivers</option><option v-for="driver in drivers" :key="driver.id" :value="String(driver.id)">{{ driver.name }}</option></TomSelect><TomSelect v-model="filters.violation_type"><option value="">All Types</option><option v-for="option in violationTypes" :key="option.value" :value="option.value">{{ option.label }}</option></TomSelect><TomSelect v-model="filters.severity"><option value="">All Severities</option><option v-for="option in severities" :key="option.value" :value="option.value">{{ option.label }}</option></TomSelect><TomSelect v-model="filters.acknowledged"><option value="">All Acknowledgment</option><option value="yes">Acknowledged</option><option value="no">Unacknowledged</option></TomSelect><Litepicker v-model="filters.date_from" :options="pickerOptions" /><Litepicker v-model="filters.date_to" :options="pickerOptions" /><div class="flex gap-3 xl:col-span-2"><Button variant="primary" class="w-full" @click="applyFilters">Apply</Button><Button variant="outline-secondary" class="w-full" @click="filters.carrier_id=''; filters.driver_id=''; filters.violation_type=''; filters.severity=''; filters.acknowledged=''; filters.date_from=''; filters.date_to=''; applyFilters()">Reset</Button></div></div></div></div>
        <div class="col-span-12"><div class="box box--stacked overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left font-semibold text-slate-600">Driver</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Carrier</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Trip</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Violation</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Severity</th><th class="px-5 py-3 text-left font-semibold text-slate-600">Date</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white"><tr v-for="row in violations.data" :key="row.id"><td class="px-5 py-4"><Link :href="route('admin.reports.violation-details', row.id)" class="font-medium text-primary hover:underline">{{ row.driver_name }}</Link></td><td class="px-5 py-4 text-slate-600">{{ row.carrier_name || 'N/A' }}</td><td class="px-5 py-4 text-slate-600">{{ row.trip_number || 'N/A' }}</td><td class="px-5 py-4 text-slate-600">{{ row.violation_type }}</td><td class="px-5 py-4 text-slate-600">{{ row.severity }}</td><td class="px-5 py-4 text-slate-600"><div>{{ row.date || 'N/A' }}</div><div class="text-xs text-slate-500">{{ row.hours_exceeded }} hours exceeded · {{ row.acknowledged ? 'Acknowledged' : 'Pending ack' }}</div></td></tr><tr v-if="!violations.data.length"><td colspan="6" class="px-5 py-10 text-center text-slate-500">No violations matched the current filters.</td></tr></tbody></table></div><div class="border-t border-slate-100 p-4"><ReportPagination :links="violations.links" /></div></div></div>
    </div>
</template>
