<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $adminMessage->subject }}</title>
    <style>
        body {
            margin: 0;
            padding: 24px;
            background: #f8fafc;
            color: #334155;
            font-family: Arial, sans-serif;
            line-height: 1.6;
        }
        .container {
            max-width: 760px;
            margin: 0 auto;
            background: #ffffff;
            border-radius: 18px;
            overflow: hidden;
            box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08);
        }
        .header {
            background: #1e3a8a;
            color: #ffffff;
            padding: 28px 32px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            line-height: 1.3;
        }
        .badge {
            display: inline-block;
            margin-top: 12px;
            padding: 6px 12px;
            border-radius: 999px;
            background: rgba(255, 255, 255, 0.18);
            color: #ffffff;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        .content {
            padding: 32px;
        }
        .message-box {
            margin: 24px 0;
            padding: 20px 22px;
            border-radius: 14px;
            background: #eff6ff;
            border-left: 4px solid #1e3a8a;
        }
        .meta {
            margin-top: 24px;
            padding: 18px 20px;
            border-radius: 14px;
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            font-size: 13px;
        }
        .meta strong {
            display: inline-block;
            width: 88px;
            color: #0f172a;
        }
        .footer {
            padding: 24px 32px;
            background: #0f172a;
            color: #cbd5e1;
            text-align: center;
            font-size: 12px;
        }
        @media (max-width: 640px) {
            body {
                padding: 12px;
            }
            .header, .content, .footer {
                padding: 22px 18px;
            }
            .meta strong {
                width: 74px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div style="font-size: 13px; letter-spacing: 0.08em; text-transform: uppercase; opacity: 0.85;">EF Services</div>
            <h1>{{ $adminMessage->subject }}</h1>
            <div class="badge">{{ ucfirst($adminMessage->priority ?? 'normal') }} priority</div>
        </div>

        <div class="content">
            <p>Hello {{ $recipient->name }},</p>

            <p>You have received a new message from the EF Services administrative team.</p>

            <div class="message-box">
                {!! nl2br(e($adminMessage->message)) !!}
            </div>

            <div class="meta">
                <div><strong>From:</strong> {{ $adminMessage->sender->name ?? 'Administrator' }}</div>
                <div><strong>Date:</strong> {{ $adminMessage->created_at->format('m/d/Y H:i') }}</div>
                <div><strong>Email:</strong> {{ $adminMessage->sender_email ?? 'N/A' }}</div>
            </div>

            <p style="margin-top: 24px; font-size: 14px; color: #64748b;">
                This message was generated by the EF Services platform. If you need help, please contact your team through the appropriate portal.
            </p>
        </div>

        <div class="footer">
            <div><strong>EF Services</strong></div>
            <div style="margin-top: 6px;">Transport and compliance operations platform</div>
            <div style="margin-top: 8px;">&copy; {{ date('Y') }} EF Services. All rights reserved.</div>
        </div>
    </div>
</body>
</html>
