<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $contactData['subject'] ?? 'Carrier Message' }}</title>
    <style>
        body { margin: 0; padding: 24px; background: #f8fafc; font-family: Arial, sans-serif; color: #1e293b; }
        .card { max-width: 640px; margin: 0 auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; }
        .header { padding: 24px; background: #0f172a; color: #ffffff; }
        .header h1 { margin: 0; font-size: 22px; }
        .header p { margin: 8px 0 0; color: #cbd5e1; font-size: 14px; }
        .content { padding: 24px; }
        .meta { margin-bottom: 20px; }
        .meta-label { font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 6px; }
        .meta-value { font-size: 15px; font-weight: 600; color: #0f172a; }
        .badge { display: inline-block; border-radius: 999px; padding: 6px 12px; font-size: 12px; font-weight: 700; text-transform: uppercase; background: #e2e8f0; color: #0f172a; }
        .message { margin-top: 18px; padding: 18px; border-radius: 14px; background: #f8fafc; border: 1px solid #e2e8f0; white-space: pre-wrap; line-height: 1.6; }
        .footer { padding: 18px 24px 24px; font-size: 12px; color: #64748b; }
    </style>
</head>
<body>
    <div class="card">
        <div class="header">
            <h1>Message from Your Carrier</h1>
            <p>You received a direct communication from the carrier operations team.</p>
        </div>

        <div class="content">
            <div class="meta">
                <div class="meta-label">Subject</div>
                <div class="meta-value">{{ $contactData['subject'] ?? 'No subject provided' }}</div>
            </div>

            @if (!empty($contactData['priority']))
                <div class="meta" style="margin-bottom: 18px;">
                    <div class="meta-label">Priority</div>
                    <span class="badge">{{ ucfirst($contactData['priority']) }}</span>
                </div>
            @endif

            @if (!empty($senderName) || !empty($senderEmail))
                <div class="meta">
                    <div class="meta-label">From</div>
                    <div class="meta-value">
                        {{ $senderName ?: 'Carrier Team' }}
                        @if (!empty($senderEmail))
                            <div style="font-size: 13px; font-weight: 400; color: #475569; margin-top: 4px;">{{ $senderEmail }}</div>
                        @endif
                    </div>
                </div>
            @endif

            <div class="meta">
                <div class="meta-label">Message</div>
                <div class="message">{{ $contactData['message'] ?? 'No content provided.' }}</div>
            </div>
        </div>

        <div class="footer">
            This email was generated by EF Services. Please contact your carrier directly if you need to follow up.
        </div>
    </div>
</body>
</html>
